package eg.edu.alexu.cse.oop.draw;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mohamed Elkalaf
 */
public class Frame extends javax.swing.JFrame {

    private DrawingEngineClass engine;
    public PaintPanel boardPanel = new PaintPanel(this);
    public ShapesButtons shapeButton;
    public  BorderLayout viewLayout = new BorderLayout();
    private String buttonText;
    String input;
    Point newPos;
    private ShapeClass currShape;
    int noOfParams;
    private Color color;
    private Color fillColor;    
    String symbol;
    Double value;
    private HashMap<String, Double> properties = new HashMap<String, Double>();    
    public Frame() { 
        shapeButton = new ShapesButtons(this);
        engine = new DrawingEngineClass();
        initComponents();
        setIcon();
        this.setTitle("Paint");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        ButtonsPanel = new javax.swing.JPanel();
        btnRedo = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        Circle = new javax.swing.JButton();
        Triangle = new javax.swing.JButton();
        Square = new javax.swing.JButton();
        btnMove = new javax.swing.JButton();
        Ellipse = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        Line = new javax.swing.JButton();
        btnColorize = new javax.swing.JButton();
        Rect = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Plugin = new javax.swing.JButton();
        comboBox1 = new javax.swing.JComboBox<>();
        NewShape = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        ButtonsPanel.setBackground(new java.awt.Color(153, 0, 153));

        btnRedo.setText("Redo");
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        Circle.setText("Circle");

        Triangle.setText("Triangle");

        Square.setText("Square");
        Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareActionPerformed(evt);
            }
        });

        btnMove.setText("Move");
        btnMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveActionPerformed(evt);
            }
        });

        Ellipse.setText("Ellipse");
        Ellipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EllipseActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        Line.setText("Line");

        btnColorize.setText("Colorize");
        btnColorize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorizeActionPerformed(evt);
            }
        });

        Rect.setText("Rect");

        btnCopy.setText("Copy");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Shape");

        Plugin.setText("Plugin");
        Plugin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PluginActionPerformed(evt);
            }
        });

        NewShape.setText("NewShape");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Shape");

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                                .addComponent(btnUndo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnRedo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCopy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMove, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnColorize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Plugin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(NewShape)))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rect)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Line)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Square)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ellipse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Triangle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Circle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnColorize)
                        .addComponent(btnDelete)
                        .addComponent(Plugin)
                        .addComponent(NewShape))
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUndo)
                            .addComponent(btnRedo)
                            .addComponent(btnEdit)
                            .addComponent(btnCopy)
                            .addComponent(btnMove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Circle)
                            .addComponent(Triangle)
                            .addComponent(Square)
                            .addComponent(Ellipse)
                            .addComponent(Line)
                            .addComponent(Rect)
                            .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Rect.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
           int index = comboBox.getSelectedIndex();
           engine.removeShape(engine.getShapes()[index]);
           engine.removecomboShape((String) comboBox.getSelectedItem());   
           engine.refreshcombo(comboBox);
           boardPanel.repaint();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed

    }//GEN-LAST:event_comboBoxActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
            newPos = new Point();
            int index = comboBox.getSelectedIndex();
            try {
                 currShape=(ShapeClass) engine.getShapes()[index].clone();
                } catch (CloneNotSupportedException ex) {
                Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
            }
            input = JOptionPane.showInputDialog(this, "x coordinate");
            newPos.x = Integer.parseInt(input);
            input = JOptionPane.showInputDialog(this, "y coordinate ");
            newPos.y = Integer.parseInt(input);
                currShape.setPosition(newPos);
                engine.addShape(currShape);
                engine.addcomboShape((String) comboBox.getSelectedItem()+"#");
            engine.refreshcombo(comboBox);
            boardPanel.repaint();
    }//GEN-LAST:event_btnCopyActionPerformed

    private void btnColorizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorizeActionPerformed
        int index = comboBox.getSelectedIndex();
        color = JColorChooser.showDialog(null, "Out Color", Color.BLACK);
        fillColor = JColorChooser.showDialog(null, "In Color", Color.WHITE);
            try {
                engine.undostep();
                engine.undocombostep();
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
            }
           engine.getShapes()[index].setColor(color);
           engine.getShapes()[index].setFillColor(fillColor);
           boardPanel.repaint();
    }//GEN-LAST:event_btnColorizeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
            int index = comboBox.getSelectedIndex();
            input = JOptionPane.showInputDialog(this, "Num of parametes");
            noOfParams = Integer.parseInt(input);

        for (int i = 1; i <= noOfParams; i++) {
            symbol = JOptionPane.showInputDialog(this, "Parameter " + i + "symbol:");
            input = JOptionPane.showInputDialog(this, "Parameter " + i + " Value:");
            value = new Double(input);
            properties.put(symbol, value);
        }
            try {
                engine.undostep();
                engine.undocombostep();
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
            }
            engine.getShapes()[index].setProperties(properties);           
        boardPanel.repaint();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveActionPerformed
            newPos = new Point();
            int index = comboBox.getSelectedIndex();
            input = JOptionPane.showInputDialog(this, "x coordinate");
            newPos.x = Integer.parseInt(input);
            input = JOptionPane.showInputDialog(this, "y coordinate");
            newPos.y = Integer.parseInt(input);
            
            
            try {
                engine.undostep();
                engine.undocombostep();
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
            }
            engine.getShapes()[index].setPosition(newPos);         
        boardPanel.repaint();
    }//GEN-LAST:event_btnMoveActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        engine.undo();  
        engine.refreshcombo(comboBox);
        boardPanel.repaint();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        engine.redo(); 
        engine.refreshcombo(comboBox);        
        boardPanel.repaint();
    }//GEN-LAST:event_btnRedoActionPerformed

    private void PluginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PluginActionPerformed
            String name = JOptionPane.showInputDialog(this, "What's Class Name");

            JFileChooser fileChooser = new JFileChooser();
            if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                {
                    try {
                        

                        URLClassLoader Loader = new URLClassLoader(new URL[]{fileChooser.getSelectedFile().toURI().toURL()}, this.getClass().getClassLoader());
                        Class newClass = Class.forName("eg.edu.alexu.cse.oop.draw." + name, true, Loader);
                        addNewButton(name, newClass);
                    } catch (IOException ex) {
                        Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(ActionListener.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_PluginActionPerformed

    private void SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SquareActionPerformed

    private void EllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EllipseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EllipseActionPerformed
          
    public DrawingEngineClass getEngine() {
        return engine;
    }
    
       public void run() throws ClassNotFoundException {
       this.setSize(1000,700);
        this.setLocationRelativeTo(null);
        
        panel.setLayout(viewLayout);
        panel.add(boardPanel , BorderLayout.CENTER);
        boardPanel.setName("board");   
        boardPanel.setBackground(Color.WHITE); 
        
        NewShape.addActionListener(shapeButton);
        Circle.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Circle"));
        Rect.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Rect"));
        Line.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Line"));
        Ellipse.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Ellipse"));
        Triangle.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Triangle"));
        Square.addActionListener(shapeButton);
        shapeButton.getEngine().installPluginShape((Class<? extends Shape>) Class.forName("eg.edu.alexu.cse.oop.draw.Square"));
      
        this.setVisible(true);  
    }
       public JFrame getFrame() {
        return this;
    }
        public PaintPanel getBoardPanel() {
        return boardPanel;
    }

    public JComboBox<String> getShapeListCombo() {
        return comboBox;
    }
    public JComboBox<String> getPShapeListCombo() {
        return comboBox1;
    }
    public static void main(String args[]) throws ClassNotFoundException {
     Frame frame = new Frame();
     frame.run();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton Circle;
    private javax.swing.JButton Ellipse;
    private javax.swing.JButton Line;
    private javax.swing.JButton NewShape;
    private javax.swing.JButton Plugin;
    private javax.swing.JButton Rect;
    private javax.swing.JButton Square;
    private javax.swing.JButton Triangle;
    private javax.swing.JButton btnColorize;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMove;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnUndo;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon256.png")));}
    public void addNewButton(String name, Class c)throws ClassNotFoundException {
        comboBox1.addItem(name);
        engine.installPluginShape(c);
    }
        public void addOldButton(Class c)throws ClassNotFoundException { 
         engine.installPluginShape(c);
    }
}
